#
# Docker file for Tilix CI tests on Debian Testing
#
FROM debian:testing

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# GtkD is no longer packaged in Debian Testing, build it from source
COPY make-install-deps-extern.sh /build/ci/
RUN chmod +x /build/ci/make-install-deps-extern.sh && /build/ci/make-install-deps-extern.sh

# finish
WORKDIR /build
